enyo.depends(
	'version.js',
	'enyo.Spotlight.js',
	'enyo.Spotlight.Util.js',
	'enyo.Spotlight.Accelerator.js',
	'enyo.Spotlight.Scrolling.js',
	'enyo.Spotlight.NearestNeighbor.js',
	'enyo.Spotlight.Muter.js',
	'enyo.Spotlight.States.js',
	'enyo.Spotlight.TestMode.js',
	'decorators',
	'css'
);
